"use client";
import { useEffect, useState } from "react";

type Dash = any;
const input: React.CSSProperties = { background:"#0f1629",color:"white",border:"1px solid #34405e",borderRadius:8,padding:"9px 10px" };
const button: React.CSSProperties = { ...input, cursor:"pointer", background:"#1b2949" };
const card: React.CSSProperties = { background:"#121a2f",border:"1px solid #28324f",borderRadius:12,padding:16,marginBottom:14 };
export default function AdminPage(){
 const [email,setEmail]=useState(""); const [d,setD]=useState<Dash>(null); const [tab,setTab]=useState("overview"); const [err,setErr]=useState(""); const [busy,setBusy]=useState(false); const [started,setStarted]=useState(0); const [elapsed,setElapsed]=useState(0);
 useEffect(()=>{setEmail(localStorage.getItem("nexusAdminEmail")||"");},[]);
 useEffect(()=>{if(!busy)return;const t=setInterval(()=>setElapsed(Math.floor((Date.now()-started)/1000)),250);return()=>clearInterval(t);},[busy,started]);
 async function load(){setBusy(true);setStarted(Date.now());setElapsed(0);setErr("");localStorage.setItem("nexusAdminEmail",email);try{const r=await fetch("/api/admin/dashboard",{headers:{"x-nexus-user":email}});const j=await r.json();if(!r.ok)throw new Error(j.error||"Forbidden");setD(j);}catch(e){setErr(e instanceof Error?e.message:"Error");}finally{setBusy(false);}}
 async function post(url:string,body:any){setBusy(true);setStarted(Date.now());setElapsed(0);setErr("");try{const r=await fetch(url,{method:"POST",headers:{"content-type":"application/json","x-nexus-user":email},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||"Error");await load();}catch(e){setErr(e instanceof Error?e.message:"Error");setBusy(false);}}
 return <main style={{minHeight:"100vh",background:"#0b1020",color:"#eef2ff",padding:24,fontFamily:"Arial,sans-serif"}}><div style={{maxWidth:1200,margin:"auto"}}><header style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",marginBottom:18}}><div><h1 style={{margin:0}}>Nexus Admin Console</h1><div style={{opacity:.65}}>Zendesk extension, centers, users, Matrix and queue controls</div></div><div style={{display:"flex",gap:8}}><input style={input} value={email} onChange={e=>setEmail(e.target.value)} placeholder="Admin email"/><button style={button} onClick={load}>Open</button></div></header>
 {busy&&<div style={card}>Loading <b>{Math.min(95,10+elapsed*5)}%</b> · {elapsed}s elapsed</div>}{err&&<div style={{...card,background:"#3a1820"}}>{err}</div>}
 {d&&<><nav style={{display:"flex",gap:7,flexWrap:"wrap",marginBottom:14}}>{["overview","users","centers","matrix","settings","audit"].map(x=><button key={x} style={{...button,opacity:tab===x?1:.6}} onClick={()=>setTab(x)}>{x}</button>)}</nav>
 {tab==="overview"&&<section style={card}><h2>System</h2><p><b>{d.me.email}</b> · {d.me.role}</p><p>Queue: <b>{d.queue.waiting}</b> waiting · <b>{d.queue.running}</b> running · average <b>{d.queue.average_job_seconds}s</b></p><p>Users: {d.users.length} · Centers: {d.centers.length} · Admin Matrix rules: {d.matrixRules.length}</p></section>}
 {tab==="users"&&<Users d={d} save={(x:any)=>post("/api/admin/users",x)}/>} {tab==="centers"&&<Centers d={d} save={(x:any)=>post("/api/admin/centers",x)}/>} {tab==="matrix"&&<Matrix d={d} save={(x:any)=>post("/api/admin/matrix",x)}/>} {tab==="settings"&&<section style={card}><h2>Server controls</h2><p>April only: maintenance and capacity controls.</p><button style={{...button,background:"#5a1f2c"}} disabled={d.me.role!=="super_admin"} onClick={()=>post("/api/admin/settings",{key:"maintenanceMode",value:true})}>Maintenance Mode</button> <button style={button} disabled={d.me.role!=="super_admin"} onClick={()=>post("/api/admin/settings",{key:"maintenanceMode",value:false})}>Resume</button><pre>{JSON.stringify(d.settings,null,2)}</pre></section>}
 {tab==="audit"&&<section style={card}><h2>Audit log</h2>{d.audit.slice(0,100).map((a:any)=><div key={a.id} style={{padding:"8px 0",borderBottom:"1px solid #28324f"}}>{new Date(a.at).toLocaleString()} · <b>{a.actor}</b> · {a.action} · {a.target}</div>)}</section>}</>}</div></main>;
}
function Users({d,save}:{d:any,save:(x:any)=>void}){const[x,s]=useState<any>({email:"",role:"agent",enabled:true});return <section style={card}><h2>Users</h2><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><input style={input} placeholder="email" value={x.email} onChange={e=>s({...x,email:e.target.value})}/><select style={input} value={x.role} onChange={e=>s({...x,role:e.target.value})}>{["agent","supervisor","trainer","admin","super_admin"].map(r=><option key={r}>{r}</option>)}</select><select style={input} value={x.centerId||""} onChange={e=>s({...x,centerId:e.target.value||undefined})}><option value="">No center</option>{d.centers.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button style={button} onClick={()=>save(x)}>Add / Update</button></div>{d.users.map((u:any)=><p key={u.email}>{u.email} · {u.role} · {u.enabled?"enabled":"disabled"}</p>)}</section>}
function Centers({d,save}:{d:any,save:(x:any)=>void}){const[x,s]=useState<any>({name:"",maxQueue:50,priority:0,enabled:true});return <section style={card}><h2>Centers</h2><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><input style={input} placeholder="Center name" value={x.name} onChange={e=>s({...x,name:e.target.value})}/><input style={input} type="number" value={x.maxQueue} onChange={e=>s({...x,maxQueue:Number(e.target.value)})}/><button style={button} onClick={()=>save(x)}>Add Center</button></div>{d.centers.map((c:any)=><p key={c.id}>{c.name} · queue {c.maxQueue} · {c.enabled?"enabled":"disabled"}</p>)}</section>}
function Matrix({d,save}:{d:any,save:(x:any)=>void}){const[x,s]=useState<any>({section:"",issue:"",instructions:"",enabled:true});return <section style={card}><h2>Admin Matrix Rules</h2><div style={{display:"grid",gap:8}}><input style={input} placeholder="Section" value={x.section} onChange={e=>s({...x,section:e.target.value})}/><input style={input} placeholder="Issue" value={x.issue} onChange={e=>s({...x,issue:e.target.value})}/><textarea style={{...input,minHeight:90}} placeholder="Instructions" value={x.instructions} onChange={e=>s({...x,instructions:e.target.value})}/><button style={button} onClick={()=>save(x)}>Publish Rule</button></div>{d.matrixRules.map((r:any)=><div key={r.id} style={{padding:"10px 0",borderBottom:"1px solid #28324f"}}><b>{r.section} — {r.issue}</b><div>{r.instructions}</div><small>v{r.version} · {r.updatedBy}</small></div>)}</section>}
